<?php
namespace App\_MODULENAME_\Presenters;

use App\Forms\_TABLENAMEUPPER_FormFactory;
use App\Service\_TABLENAMEUPPER_Service;
use Nette;
use App\Model;


class _TABLENAMEUPPER_Presenter extends BasePresenter
{

    /** @persistent */
    public $lock = 0;

    /** @persistent */
    public $quickFlash = "";

    /** @var _TABLENAMEUPPER_Service @inject */
    private $_TABLENAME_Service;

    /** @var _TABLENAMEUPPER_FormFactory @inject */
    public $_TABLENAME_FormFactory;

    public function __construct(_TABLENAMEUPPER_Service $_TABLENAME_Service)
    {
        $this->_TABLENAME_Service = $_TABLENAME_Service;

    }

    public function actionDefault()
    {
        parent::actionDefault(); // TODO: Change the autogenerated stub
    }

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    public function renderDefault()
	{
		$this->template->list = $this->_TABLENAME_Service->getList();
	}

    protected function createComponent_TABLENAMEUPPER_Form()
    {
        return $this->_TABLENAME_FormFactory->create(function () {});
    }

    public function handleEdit_TABLENAMEUPPER_($id = null){
        $this->template->edit_TABLENAMEUPPER_ = true;
        $this->template->id_TABLENAMEUPPER_ = $id;

        if (($id != null)){

            $_TABLENAME_ = $this->_TABLENAME_Service->getBy($id);
            $_TABLENAME_Model = new Model\_TABLENAMEUPPER_Model($_TABLENAME_);

            $this['_TABLENAME_Form']->setDefaults($_TABLENAME_);

        }
        if ($this->isAjax()) {
            $this->redrawControl('edit_TABLENAMEUPPER_');
        }else{
            $this->redirect(":Admin:_TABLENAMEUPPER_:default");
        }
    }

    public function handleDelete_TABLENAMEUPPER_($id){
        $_TABLENAME_Model = new Model\_TABLENAMEUPPER_Model($this->_TABLENAME_Service->getBy($id));
        $this->_TABLENAME_Service->delete($_TABLENAME_Model);
        if ($this->isAjax()) {
            $this->redrawControl('obsah');
        }else{
            $this->redirect(":Admin:_TABLENAMEUPPER_:default");
        }
    }

}
