<?php
namespace App\StockModule\Presenters;

use App\Forms\RentalFormFactory;
use App\Service\RentalService;
use Nette;
use App\Model;


class RentalPresenter extends BasePresenter
{

    /** @persistent */
    public $lock = 0;

    /** @persistent */
    public $quickFlash = "";

    /** @var RentalService @inject */
    private $rentalService;

    /** @var RentalFormFactory @inject */
    public $rentalFormFactory;

    public function __construct(RentalService $rentalService)
    {
        $this->rentalService = $rentalService;

    }

    public function actionDefault()
    {
        parent::actionDefault(); // TODO: Change the autogenerated stub
    }

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    public function renderDefault()
	{
		$this->template->list = $this->rentalService->getList();
	}

    protected function createComponentRentalForm()
    {
        return $this->rentalFormFactory->create(function () {});
    }

    public function handleEditRental($id = null){
        $this->template->editRental = true;
        $this->template->idRental = $id;

        if (($id != null)){

            $rental = $this->rentalService->getBy($id);
            $rentalModel = new Model\RentalModel($rental);

            $this['rentalForm']->setDefaults($rental);

        }
        if ($this->isAjax()) {
            $this->redrawControl('editRental');
        }else{
            $this->redirect(":Admin:Rental:default");
        }
    }

    public function handleDeleteRental($id){
        $rentalModel = new Model\RentalModel($this->rentalService->getBy($id));
        $this->rentalService->delete($rentalModel);
        if ($this->isAjax()) {
            $this->redrawControl('obsah');
        }else{
            $this->redirect(":Admin:Rental:default");
        }
    }

}
